name: Autograder
description: Executes .exe tests based on autograding.json and updates the GitHub check run with the results.
author: Millie Bourgois
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'check-circle'
  color: 'blue'
